# Generated by Django 6.0.3 on 2026-05-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='service_type',
            field=models.CharField(choices=[('SERVICE_CLIENT_MULTICANAL', 'Service client multicanal'), ('GUICHET_ADMINISTRATIF', 'Guichet administratif'), ('SUPPORT_TECHNIQUE', 'Support technique (ticketing)'), ('DRIVE_RESTAURANT', 'Drive de restaurant'), ('HOPITAL_URGENCES', 'Hôpital – Urgences'), ('CENTRE_VACCINATION', 'Centre de vaccination')], default='SERVICE_CLIENT_MULTICANAL', max_length=50, verbose_name='Type de service'),
        ),
    ]
