# Generated by Django 6.0.3 on 2026-06-02 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queueapp', '0002_queue_service_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('agent_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('busy', 'Occupé'), ('break', 'Pause'), ('offline', 'Hors ligne')], default='available', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='served_by', to='queueapp.queueitem')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='queueapp.queue')),
            ],
            options={
                'ordering': ['agent_number'],
                'unique_together': {('queue', 'agent_number')},
            },
        ),
    ]
