# Generated by Django 6.0.3 on 2026-06-22 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queueapp', '0006_alter_queue_service_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queue',
            options={'ordering': ['name']},
        ),
    ]
